{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rate-your-mate.fullname" . }}-secrets
  labels:
    {{- include "rate-your-mate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.steamApiKey }}
  STEAM_API_KEY: {{ .Values.secrets.steamApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.adminPassword }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | b64enc | quote }}
  {{- end }}
{{- end }}
