{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lan-party-manager.fullname" . }}-secrets
  labels:
    {{- include "lan-party-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.steamApiKey }}
  STEAM_API_KEY: {{ .Values.secrets.steamApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- end }}
{{- end }}
